blockExoticSubdeps: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@swc/core"
  - bcrypt
  - less
  - nx
  - prisma
  - protobufjs
  - unrs-resolver

autoInstallPeers: true
