services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    container_name: englishdb
    user: ${POSTGRES_USER:-postgres}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-englishdb}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB:-englishdb} -U $${POSTGRES_USER:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api-network
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
      - "${REDIS_INSIGHT_PORT:-8001}:8001"
    networks:
      - api-network
    volumes:
      - redis-data:/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT:-8080}:8080
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  postgresql-data:
  redis-data:
