export enum Badge {
	LOGIN_SEVEN_DAYS_STREAK = 'LOGIN_SEVEN_DAYS_STREAK',
	LOGIN_TWO_WEEKS_STREAK = 'LOGIN_TWO_WEEKS_STREAK',
	LOGIN_ONE_MONTH_STREAK = 'LOGIN_ONE_MONTH_STREAK',
	LOGIN_ONE_YEAR_STREAK = 'LOGIN_ONE_YEAR_STREAK',

	LOGIN_SEVEN_DAYS = 'LOGIN_SEVEN_DAYS',
	LOGIN_TWO_WEEKS = 'LOGIN_TWO_WEEKS',
	LOGIN_ONE_MONTH = 'LOGIN_ONE_MONTH',
	LOGIN_ONE_YEAR = 'LOGIN_ONE_YEAR',

	FIRST_COMPLETE_ATTEMPT = 'FIRST_COMPLETE_ATTEMPT',
	TENTH_COMPLETE_ATTEMPT = 'TENTH_COMPLETE_ATTEMPT',
	HUNDREDTH_COMPLETE_ATTEMPT = 'HUNDREDTH_COMPLETE_ATTEMPT',

	FIRST_GOOD_SCORE = 'FIRST_GOOD_SCORE',
	TENTH_GOOD_SCORE = 'TENTH_GOOD_SCORE',
	HUNDREDTH_GOOD_SCORE = 'HUNDREDTH_GOOD_SCORE',

	FIRST_PERFECT_SCORE = 'FIRST_PERFECT_SCORE',
	TENTH_PERFECT_SCORE = 'TENTH_PERFECT_SCORE',
	HUNDREDTH_PERFECT_SCORE = 'HUNDREDTH_PERFECT_SCORE',
}

export enum BadgeType {
	LOGIN = 'LOGIN',
	ATTEMPT_COUNT = 'ATTEMPT_COUNT',
	ATTEMPT_SCORE = 'ATTEMPT_SCORE',
}
