name: Dev CI/CD Pipeline

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci @swc/cli @swc/core

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build app
        run: npm run build
